version: "3"

services:
    mongodb:
        image: mongo
        container_name: ft-mongodb
        restart: unless-stopped
        environment:
            PUID: "1000"
            PGID: "1000"
            TZ: "Asia/Singapore"
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "example"
        volumes:
            - ./mongo/data:/data/db
    fastapi:
        build:
            context: ./src/
            dockerfile: Dockerfile
        container_name: ft-fastapi
        restart: unless-stopped
        depends_on:
            - "mongodb"
        ports:
            - 8000:8000
        environment:
            PUID: "1000"
            PGID: "1000"
            TZ: "Asia/Singapore"
            # MongoDB configs
            _DB_NAME: "dev" # any name
            _DB_USER: "root" # keep consistent with MONGO_INITDB_ROOT_USERNAME
            _DB_PASS: "example" # keep consistent with MONGO_INITDB_ROOT_PASSWORD
            _DB_SERVICE: "mongodb" # keep consistent with db service name
            _DB_PORT: "27017" # default mongodb port: 27017
            # SSL secret key for JWT authentication
            # use command 'openssl rand -hex 32' to generate a random key
            JWT_SECRET_KEY_PROD: "REPLACE_ME"
            # FastAPI configs
            PORT: "8000"
            MODULE_NAME: "api.main"
            LOG_LEVEL: "debug"
            PRE_START_PATH: "/app/api/prestart.sh"
            # Gunicorn configs
            MAX_WORKERS: "1" # number of Gunicorn workers
        volumes:
            - "./logs:/app/logs"
            - "./local_db:/app/api/local_db"
