curl -i -X 'DELETE' \
  'http://0.0.0.0:8000/api/records/' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer PASTE_YOUR_TOKEN_HERE' \
  -H 'Content-Type: application/json' \
  -d '{"imported": true}'