curl -i -X 'POST' \
  'http://0.0.0.0:8000/api/records/import' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer PASTE_YOUR_TOKEN_HERE' \
  -H 'Content-Type: multipart/form-data' \
  -F 'file=@demo/dbs_statement.csv;type=text/csv'