version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb-test
        environment:
            PUID: "1000"
            PGID: "1000"
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "example"
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
